version: '3.8'
services:
  apigateway:
    container_name: apigateway
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
    ports:
      - "8082:8082"
  auth2:
    container_name: auth2
    build:
      dockerfile: Dockerfile
      context: ./database
  book:
    container_name: book
    build:
      dockerfile: Dockerfile
      context: ./golang
networks:
  default:
    name: network1
    driver: bridge